name: Issues Management

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  manage-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Issues Helper
        uses: actions-cool/issues-helper-backup@main # TODO: github is black and disabled the original repo, so we have to use this.
        with:
          actions: |
            close-issues
            reply-when-label
            remove-labels
            check-keyword
          token: ${{ secrets.GITHUB_TOKEN }}
          close-labels: stale
          inactive-day: 7
          reply-labels: needs-info
          reply-comment: |
            👋 Thanks for tagging this issue with `needs-info`.  
            Please provide the requested details so we can help you better!
          remove-labels: waiting-for-response
          keywords: 'fixed, resolved'
